import { z } from "zod";

export const WaitlistBody = z.object({
  email: z.string().trim().email().max(254),
  /** Honeypot — real users never see this field; any value marks a bot.
   * No max(0): the field must VALIDATE so the route can answer a fake
   * success (a 400 would tip the bot off). */
  company: z.string().optional(),
  /** Optional Instagram handle — never blocks signup; anything that
   * doesn't normalize to a valid handle is silently dropped. */
  insta: z.string().max(64).optional(),
  /** Referral code from ?ref= — verified against the base by the route;
   * unknown codes are silently ignored, never an error. */
  ref: z.string().trim().max(12).optional(),
  utm: z.record(z.string()).optional(),
});

export type WaitlistBodyType = z.infer<typeof WaitlistBody>;

/**
 * Normalize an Instagram handle: trim, lowercase, strip one leading @.
 * Returns null when the result isn't a plausible handle — the caller
 * ignores it silently (spec: the field must never block a signup).
 */
export function normalizeInsta(raw: string | undefined): string | null {
  if (!raw) return null;
  const handle = raw.trim().toLowerCase().replace(/^@/, "");
  return /^[a-z0-9._]{1,30}$/.test(handle) ? handle : null;
}

/** Referral codes as generated by gen_ref_code() (6 chars today; the
 * bounds are loose so a future alphabet tweak needs no code change). */
export function isValidRefCode(code: string): boolean {
  return /^[a-z0-9]{4,12}$/.test(code);
}

export const QuizBody = z.object({
  email: z.string().trim().email().max(254),
  /** Honeypot — see WaitlistBody.company. */
  company: z.string().optional(),
  /** The five-energy spectrum, e.g. { "L'Onde": 42, "Le Murmure": 24, ... }.
   * Kept as an open record (not a fixed 5 keys) so the quiz copy can evolve
   * without a schema migration; values are clamped 0–100, 1–12 entries. */
  scores: z
    .record(z.string().max(40), z.number().finite().min(0).max(100))
    .refine((s) => Object.keys(s).length >= 1 && Object.keys(s).length <= 12, {
      message: "scores must have 1–12 entries",
    }),
  /** Derived diva-profile label; the route falls back to the top energy. */
  profile: z.string().max(80).optional(),
  utm: z.record(z.string()).optional(),
});

export type QuizBodyType = z.infer<typeof QuizBody>;
