import { chromium } from "playwright-core";
const browser = await chromium.launch({ executablePath: "/Users/meghanregior/Library/Caches/ms-playwright/chromium-1140/chrome-mac/Chromium.app/Contents/MacOS/Chromium" });
const page = await browser.newPage({ viewport: { width: 1512, height: 900 } });
const errs = [];
page.on("pageerror", e => errs.push(String(e).slice(0,200)));
page.on("console", m => { if (m.type()==="error") errs.push(m.text().slice(0,200)); });
await page.goto("http://localhost:4123/", { waitUntil: "networkidle" });
await page.waitForTimeout(5000);
await page.screenshot({ path: ".context/shots/vinyl-closed.png", clip: { x: 1330, y: 10, width: 182, height: 150 } });
await page.click("[data-vinyl]");
await page.waitForTimeout(2500);
await page.screenshot({ path: ".context/shots/vinyl-open.png", clip: { x: 1140, y: 10, width: 372, height: 330 } });
console.log("errors:", errs.filter(e => !e.includes("open.spotify")).length ? errs : "none (spotify iframe noise filtered)");
await browser.close();
